-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text,
  price numeric not null,
  stock integer default 0,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for Products
alter table public.products enable row level security;

-- Allow read access to everyone
create policy "Products are viewable by everyone" on public.products
  for select using (true);

-- Allow insert/update/delete only to admins (we'll assume service_role for migration script)
-- For now, we can allow public read, and restrict write.

-- Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  total_amount numeric not null,
  status text default 'pending',
  shipping_address jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.orders enable row level security;

-- Users can view their own orders
create policy "Users can view their own orders" on public.orders
  for select using (auth.uid() = user_id);

-- Users can insert their own orders
create policy "Users can create their own orders" on public.orders
  for insert with check (auth.uid() = user_id);

-- Order Items Table
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders on delete cascade not null,
  product_id bigint references public.products not null,
  quantity integer not null,
  price_at_purchase numeric not null
);

alter table public.order_items enable row level security;

create policy "Users can view their own order items" on public.order_items
  for select using (
    exists (
      select 1 from public.orders
      where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
    )
  );

create policy "Users can create their own order items" on public.order_items
  for insert with check (
    exists (
      select 1 from public.orders
      where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
    )
  );

-- Cart Items Table (Optional, for persistent cart)
create table public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references public.products not null,
  quantity integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

alter table public.cart_items enable row level security;

create policy "Users can view their own cart" on public.cart_items
  for select using (auth.uid() = user_id);

create policy "Users can insert their own cart" on public.cart_items
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own cart" on public.cart_items
  for update using (auth.uid() = user_id);

create policy "Users can delete their own cart" on public.cart_items
  for delete using (auth.uid() = user_id);
