
const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

// Configuration
const SUPABASE_URL = 'https://qqpxeesbqcbhtdlzzpkm.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_MvDrO8Hxm9FmWOuo3iltsg_YffWY9bb';

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

async function migrateProducts() {
    try {
        // Read local products
        const productsPath = path.join(__dirname, '../backend/data/products.json');
        const productsData = fs.readFileSync(productsPath, 'utf8');
        const products = JSON.parse(productsData);

        console.log(`Found ${products.length} products to migrate.`);

        // Transform data if necessary (remove 'id' if you want Supabase to auto-generate, 
        // but we kept 'id' in the schema as bigint generated by default, so we can insert it if we want to preserve IDs)
        // However, if the schema says "generated by default as identity", we can insert explicit IDs.

        const { data, error } = await supabase
            .from('products')
            .upsert(products, { onConflict: 'id' })
            .select();

        if (error) {
            console.error('Error migrating products:', error);
        } else {
            console.log('Successfully migrated products:', data.length);
        }

    } catch (err) {
        console.error('Migration failed:', err);
    }
}

migrateProducts();
